from imagic import Imagic
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(872, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainwidget = QtWidgets.QWidget(self.centralwidget)
        self.mainwidget.setGeometry(QtCore.QRect(0, 0, 871, 471))
        self.mainwidget.setObjectName("mainwidget")
        self.logo = QtWidgets.QLabel(self.mainwidget)
        self.logo.setGeometry(QtCore.QRect(340, 110, 157, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.downloadbutton = QtWidgets.QPushButton(self.mainwidget)
        self.downloadbutton.setGeometry(QtCore.QRect(300, 230, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.downloadbutton.setFont(font)
        self.downloadbutton.setObjectName("downloadbutton")
        self.uploadbutton = QtWidgets.QPushButton(self.mainwidget)
        self.uploadbutton.setGeometry(QtCore.QRect(300, 300, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.uploadbutton.setFont(font)
        self.uploadbutton.setObjectName("uploadbutton")
        self.uploadwidget = QtWidgets.QWidget(self.centralwidget)
        self.uploadwidget.setGeometry(QtCore.QRect(-1, -1, 871, 471))
        self.uploadwidget.setObjectName("uploadwidget")
        self.imagelabel = QtWidgets.QLabel(self.uploadwidget)
        self.imagelabel.setGeometry(QtCore.QRect(20, 20, 831, 371))
        self.imagelabel.setText("")
        self.imagelabel.setObjectName("imagelabel")
        self.uploadlabel = QtWidgets.QLabel(self.uploadwidget)
        self.uploadlabel.setGeometry(QtCore.QRect(40, 420, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.uploadlabel.setFont(font)
        self.uploadlabel.setObjectName("uploadlabel")
        self.uploadsearchtext = QtWidgets.QLineEdit(self.uploadwidget)
        self.uploadsearchtext.setGeometry(QtCore.QRect(220, 420, 211, 31))
        self.uploadsearchtext.setObjectName("uploadsearchtext")
        self.uploadimage = QtWidgets.QPushButton(self.uploadwidget)
        self.uploadimage.setGeometry(QtCore.QRect(720, 420, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.uploadimage.setFont(font)
        self.uploadimage.setObjectName("uploadimage")
        self.uploadcancelbutton = QtWidgets.QPushButton(self.uploadwidget)
        self.uploadcancelbutton.setGeometry(QtCore.QRect(620, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.uploadcancelbutton.setFont(font)
        self.uploadcancelbutton.setObjectName("uploadcancelbutton")
        self.downloadwidget = QtWidgets.QWidget(self.centralwidget)
        self.downloadwidget.setGeometry(QtCore.QRect(-1, -1, 871, 471))
        self.downloadwidget.setObjectName("downloadwidget")
        self.searchlabel = QtWidgets.QLabel(self.downloadwidget)
        self.searchlabel.setGeometry(QtCore.QRect(200, 210, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.searchlabel.setFont(font)
        self.searchlabel.setObjectName("searchlabel")
        self.searchtext = QtWidgets.QLineEdit(self.downloadwidget)
        self.searchtext.setGeometry(QtCore.QRect(200, 260, 211, 31))
        self.searchtext.setObjectName("searchtext")
        self.searchbutton = QtWidgets.QPushButton(self.downloadwidget)
        self.searchbutton.setGeometry(QtCore.QRect(720, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.searchbutton.setFont(font)
        self.searchbutton.setObjectName("searchbutton")
        self.downloadlabel = QtWidgets.QLabel(self.downloadwidget)
        self.downloadlabel.setGeometry(QtCore.QRect(190, 90, 323, 46))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.downloadlabel.setFont(font)
        self.downloadlabel.setObjectName("downloadlabel")
        self.downloadcancelbutton = QtWidgets.QPushButton(self.downloadwidget)
        self.downloadcancelbutton.setGeometry(QtCore.QRect(620, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.downloadcancelbutton.setFont(font)
        self.downloadcancelbutton.setObjectName("downloadcancelbutton")
        self.mainwidget.show()
        self.uploadwidget.hide()
        self.downloadwidget.hide()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.downloadbutton.clicked.connect(self.downloadbutton_onclick)
        self.uploadbutton.clicked.connect(self.uploadbutton_onclick)
        self.downloadcancelbutton.clicked.connect(self.downloadcancelbutton_onclick)
        self.uploadcancelbutton.clicked.connect(self.uploadcancelbutton_onclick)
        self.uploadimage.clicked.connect(self.uploadimage_onclick)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Imagic - Upload and Download Images"))
        self.logo.setText(_translate("MainWindow", "Imagic"))
        self.downloadbutton.setText(_translate("MainWindow", "Download images"))
        self.uploadbutton.setText(_translate("MainWindow", "Upload Images"))
        self.uploadlabel.setText(_translate("MainWindow", "Insert category:"))
        self.uploadimage.setText(_translate("MainWindow", "Upload"))
        self.uploadcancelbutton.setText(_translate("MainWindow", "Cancel"))
        self.searchlabel.setText(_translate("MainWindow", "Insert category:"))
        self.searchbutton.setText(_translate("MainWindow", "Search"))
        self.downloadlabel.setText(_translate("MainWindow", "Download images"))
        self.downloadcancelbutton.setText(_translate("MainWindow", "Cancel"))

    def downloadbutton_onclick(self):
        self.downloadwidget.show()
        self.mainwidget.hide()

    def uploadbutton_onclick(self):
        file_dialog = QtWidgets.QFileDialog(self.mainwidget)
        file_dialog.setFileMode(QtWidgets.QFileDialog.ExistingFile)
        file_dialog.setNameFilter("Images (*.jpg *.png *.gif *tif)")
        if file_dialog.exec_():
            file_name = file_dialog.selectedFiles()[0]
            imagic.validate_image(file_name)
            image_pixmap = QtGui.QPixmap()
            image_pixmap.loadFromData(QtCore.QByteArray(imagic.current_image.image_file))
            width = self.imagelabel.width()
            height = self.imagelabel.height()
            self.imagelabel.setPixmap(image_pixmap.scaled(width, height, QtCore.Qt.KeepAspectRatio))
            self.imagelabel.setAlignment(QtCore.Qt.AlignCenter)
            self.uploadwidget.show()
            self.mainwidget.hide()

    def uploadimage_onclick(self):
        imagic.select_category(self.uploadsearchtext.text())
        imagic.upload_image()
        self.uploadwidget.show()
        self.mainwidget.show()

    def downloadcancelbutton_onclick(self):
        self.mainwidget.show()
        self.downloadwidget.hide()

    def uploadcancelbutton_onclick(self):
        self.mainwidget.show()
        self.uploadwidget.hide()


if __name__ == "__main__":
    import sys
    imagic = Imagic()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
