#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

//CONNECTOR
#define CONNECTOR_ADDRESS "127.0.0.1"
#define CONNECTOR_FIRST_PORT 5900
#define CONNECTOR_OFFSET_PORT 10
#define QUEUE_LENGTH_CONNECTIONS 5
#define N_SERVER 3

//HEADER
#define HEADER_LENGTH 9

#endif //SERVER_CONSTANTS_H
