#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

//CONNECTOR
#define CONNECTOR_ADDRESS "127.0.0.1"
#define CONNECTOR_FIRST_PORT 40000
#define CONNECTOR_PORT_STRIDE 10
#define QUEUE_LENGTH_CONNECTIONS 5
#define N_SERVER 1

//MESSAGE
#define CHUNK_SIZE 8192

//HEADER
#define HEADER_LENGTH 9

#endif //SERVER_CONSTANTS_H
