#ifndef SERVER_CONSTANTS_H
#define SERVER_CONSTANTS_H

//CONNECTOR
#define CONNECTOR_CLIENT_ADDRESS "127.0.0.1"
#define CONNECTOR_CLIENT_PORT 5000
#define CONNECTOR_SERVER_ADDRESS "127.0.0.1"
#define CONNECTOR_SERVER_FIRST_PORT 6000
#define CONNECTOR_SERVER_OFFSET_PORT 10
#define BUFFER_SIZE 10000000 //bytes
#define QUEUE_LENGTH_CONNECTIONS 5

//HEADER
#define HEADER_LENGTH 9

typedef enum : unsigned char {
    UPLOAD_IMAGE = 0,
    VIEW_THUMBS = 1,
    DOWNLOAD_IMAGE = 2
} MESSAGE_TYPE;

#endif //SERVER_CONSTANTS_H
