STATEMENTS="CREATE DATABASE IF NOT EXISTS ${DB_NAME}_${SERVER_ID};
CREATE USER IF NOT EXISTS
  '$DB_USER'@'%' identified by '$DB_PASSWORD';
GRANT ALL ON ${DB_NAME}_${SERVER_ID}.* TO '$DB_USER'@'%';
CREATE TABLE IF NOT EXISTS ${DB_NAME}_${SERVER_ID}.$DB_TABLE_NAME (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  hash VARCHAR(45) NOT NULL,
  file_name VARCHAR(45) NOT NULL,
  thumb_file_name VARCHAR(45) NOT NULL,
  category VARCHAR(45) NOT NULL
) ENGINE = InnoDB;"
