STATEMENTS="CREATE DATABASE IF NOT EXISTS $DB_NAME$ID;
CREATE USER IF NOT EXISTS
  '$DB_USER'@'%' identified by '$DB_PASSWORD';
GRANT ALL ON $DB_NAME$ID.* TO '$DB_USER'@'%';
CREATE TABLE IF NOT EXISTS $DB_NAME$ID.$DB_TABLE_NAME (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  image_file_path VARCHAR(45) NULL,
  thumb_file_path VARCHAR(45) NULL,
  category VARCHAR(45) NULL
) ENGINE = InnoDB;"
